### ISSUE TITLE
Coated Textures Generated Normals

### ISSUE THREAD

**Issue by al-wei** [EuphoriaPatches/EuphoriaPatcher#10]
ComplementaryUnbound_r5.1.1 + EuphoriaPatches_1.2
![image](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/145486869/9984659f-4eb2-40a8-a107-be92fcea5745)
![image](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/145486869/d2fadb10-81c7-418d-8d94-78051f4f9baa)
![image](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/145486869/ad6ded2a-5228-4e9f-b5fe-ed6e0bc477ed)

ComplementaryReimagined_r5.1.1 + EuphoriaPatches_1.2
![image](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/145486869/da4a1beb-c9ab-4f55-87cc-fd2f87e94bc1)

ComplementaryUnbound_r5.1.1
![image](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/145486869/7f0135e4-3bad-437b-bf6b-37842c6d00b9)

**Comment by SpacEagle17** [comment]
Flywheel issue, nothing we can do
https://github.com/leon-o/iris-flw-compat/issues/89
