### ISSUE TITLE
Purple End Fire doesnt work when True Ending is installed

### ISSUE THREAD

**Issue by nco2k** [EuphoriaPatches/EuphoriaPatcher#11]
Purple End Fire doesnt work when [True Ending: Ender Dragon Overhaul](https://modrinth.com/datapack/true-ending) is installed. i assume its because the mod uses soul fire instead of regular fire.

![end crystal](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/26080123/a695dd10-3406-4e5a-8169-95493b51e427)

**Comment by SpacEagle17** [comment]
Yeah that is the case and I won't change that

**Comment by nco2k** [comment]
why not? you replace regular fire with purple fire. why not also replace soul fire with purple fire? is there a technical reason behind it?

**Comment by SpacEagle17** [comment]
The reason behind this is that I don't want to change the soul fire. The soul sand Valley overhaul option changes regular fire and this as well.
