### ISSUE TITLE
complementary updated

### ISSUE THREAD

**Issue by loti1234** [EuphoriaPatches/EuphoriaPatcher#12]
and now euphoria patches doesn't generate its modified complementary files
this prob also doesn't work on 1.19.2 forge and prob upwards/downwards in versions

![image](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/140719665/6fe1ac0a-1e46-4320-ac44-47b9a5ae7217)

**Comment by SpacEagle17** [comment]
A forge version was just now released, you have to get the new EP version :)
