### ISSUE TITLE
Lava Noise / Edge not working

### ISSUE THREAD

**Issue by nco2k** [EuphoriaPatches/EuphoriaPatcher#13]
i cant get lava noise / edge to work. any idea what might be causing this? changing the lava preset doesnt do anything either.

![lava](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/26080123/36a8a763-68be-4d43-8344-8513647c18b9)

**Comment by SpacEagle17** [comment]
You need to enable advanced colored lighting in the performance tab in the Complementary settings. Does not work on Mac

**Comment by nco2k** [comment]
i have it enabled, and im using windows. any other suggestions?

**Comment by SpacEagle17** [comment]
Are you using ipbr?

**Comment by nco2k** [comment]
im using labPBR with the AVPBR texture pack. switching to iPBR works, but then the textures dont look nearly as good. any chance to make it work with labPBR?

**Comment by SpacEagle17** [comment]
I'm the future, yes. In the past I tried to make these features compatible with labpbr, but that made spaghetti code so I undid that. I'll have to see if I can find a clean way to combine both
