### ISSUE TITLE
Going to the end disables the shaderpack.

### ISSUE THREAD

**Issue by DogeKingChris** [EuphoriaPatches/EuphoriaPatcher#14]
deferred1.fsh: deferred1.fsh: ERROR: 0:1101: 'GetEnderStars' : no matching overloaded function found 
ERROR: 0:1101: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

^^^^^
It gave me this error. I guess it's something to do with the stars

**Comment by DogeKingChris** [comment]
This doesn't happen on the version prior to the one i'm using. I use the latest, 1.3.3

**Comment by SpacEagle17** [comment]
Can you share your settings on discord? But I believe that I fixed this in a dev version

**Comment by SpacEagle17** [comment]
You can also share the settings file here :)

**Comment by DogeKingChris** [comment]
Alright

**Comment by DogeKingChris** [comment]
[ComplementaryReimagined_r5.2.1 + EuphoriaPatches_1.3.1.txt](https://github.com/user-attachments/files/16057153/ComplementaryReimagined_r5.2.1.%2B.EuphoriaPatches_1.3.1.txt)

**Comment by SpacEagle17** [comment]
Seems like I already fixed it in a dev version
