### ISSUE TITLE
Lava edges with blocks should be darker, not lighter

### ISSUE THREAD

**Issue by tresabhi** [EuphoriaPatches/EuphoriaPatcher#16]
![image](https://github.com/user-attachments/assets/74213a9e-3dd4-496d-8f61-86cb4cc8ecd9)

The edges between lava and the basalt blocks shouldn't be bright since lava in those spots would be cooler; hence, darker than the rest of the lava pool.

**Comment by SpacEagle17** [comment]
I thought more of the lava moving more against the rocks and by that the dark spots would break up
