### ISSUE TITLE
Log spam Iris Flywheel Compat when entity shadows is enabled

### ISSUE THREAD

**Issue by ThatKatNaps** [EuphoriaPatches/EuphoriaPatcher#18]
When using Euphoria Patches and Iris Flywheel Compat, and having the entity shadows enabled, the log gets spammed errors similar to the one below

OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.'

I am aware of previous issues regarding compatibility between Euphoria Patches and Iris Flywheel Compat, and am submitting this issue to both boards

**Comment by SpacEagle17** [comment]
Should be fixed with iris flywheel compat mod 1.1.2
