### ISSUE TITLE
Euphoria patches causing fps drop

### ISSUE THREAD

**Issue by VaporeonScripts** [EuphoriaPatches/EuphoriaPatcher#19]
using euphoria patches aslong with complementary unbound with same exact settings casues euphoria+unbound shader to drop fps and less fps overall

**Comment by SpacEagle17** [comment]
same exact settings? what fps drop are we talking about here?

**Comment by VaporeonScripts** [comment]
Like,less fps in general and ofc,worse fps drops,I used same exact complementary unbound settings,without touching euphoria patcher ones

**Comment by om3ga6400** [comment]
> Like,less fps in general and ofc,worse fps drops,I used same exact complementary unbound settings,without touching euphoria patcher ones

I think they want a specific count or example

**Comment by VaporeonScripts** [comment]
anyways,i dont use it anymore,so ig
