### ISSUE TITLE
World curvature & Lava adaptive noise

### ISSUE THREAD

**Issue by eilamg** [EuphoriaPatches/EuphoriaPatcher#2]
Hi,

There's an issue that pops up when using both World Curvature and the Adaptive Noise setting for lava.
Easier to show than describe, so I've attached with/without images for comparison.

Without curvature:
![without_curvature](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/4570254/6ed80e91-7b28-4d83-b534-b34011f42035)

With curvature:
![with_curvature](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/4570254/ffbae996-6e62-497f-9db6-1de92b77247f)

Cheers

**Comment by SpacEagle17** [comment]
Unfortunately this is not really fixable because of how world curvature works. That's the reason as well why world curvature is under the fun category as it breaks many other effects
