### ISSUE TITLE
[Feature equest] Support BYG and other mods modded sand

### ISSUE THREAD

**Issue by vgrynch** [EuphoriaPatches/EuphoriaPatcher#22]
Some custom sand and sandstone blocks look too different compared to the normal sand and red sand blocks. Can the support of modded sands be added? The below image is done in 1.19.2, using shaders v. 5.2.2, EuphoriaPatcher-0.3.4-forge.jar. The pink sand is byg:pink_sand, and 2 blocks of it's sandstone. I have tried adding these to the block.properties file, but no effect. Or is there something I should do in addition to adding them to the block.properties? 

![image](https://github.com/user-attachments/assets/447084d7-df56-47be-ba11-1285c4fe9161)

**Comment by vgrynch** [comment]
Also, is there any documentation/tutorial on how to add some mod to be supported? I have a few mods in my custom modpack that I would like to be supported by the shader too. If I know how to do it, I can share my work here to add these mods here too.

**Comment by SpacEagle17** [comment]
Feel free to join my discord server people always help there regarding such topics and explain how to help adding new blocks https://euphoriapatches.com/discord
