### ISSUE TITLE
[1.19.2] some additional lanterns colored light is wrong on the wall

### ISSUE THREAD

**Issue by vgrynch** [EuphoriaPatches/EuphoriaPatcher#23]
See the image below. Placed on the ground it is correct green. Placed on the wall it is not. Vanilla soul lantern works correctly.
Shader version 5.2.2, EuphoriaPatcher-0.3.4-forge.jar. The mod with lanterns is "Additional lanterns"

![image](https://github.com/user-attachments/assets/107134c5-f33f-4e03-b17d-dd94112bef59)

**Comment by SpacEagle17** [comment]
I am not sure if this is fixable as I believe the mod renders the hanging lantern in a weird undetectable way.
Also there is a new Euphoria and Complementary version out on Modrinth. r5.3 and Euphoria Patches 1.4.1
