### ISSUE TITLE
Block Entities behave weirdly and random artefacts on the screen with modpack (caused by flywheel compat mod)

### ISSUE THREAD

**Issue by DefinedAscent** [EuphoriaPatches/EuphoriaPatcher#3]
Enabling generated normals or coated textures with version 0.2 forge causes the following issue to occur. Does not occur without euphoria patches. Previous version 0.1.1 works fine with current load order as well.
![2023-12-23_18 29 33](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/50063694/1dc644f6-29a3-4eb7-8fb6-775c82a03e58)

![2023-12-23_18 29 28](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/50063694/395231cc-7316-4297-b9f0-032b7a31622d)

**Comment by isuewo** [comment]
This is indeed a weird issue, but it's unlikely that Euphoria Patches is the direct cause. Can you please take a screenshot of your F3 menu and describe what you're looking at, including information about the mod this is related to?

**Comment by qingchunnh** [comment]
I'm having the same problem and here's what my log says:
`[Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <program> has not been linked, or is not a program object.'
[Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. generated. <program> object is not successfully linked, or is not a program object.'`
Keeps repeating...  

---
And this problem doesn't happen when I use ComplementaryUnbound_r5.1.1.zip

**Comment by qingchunnh** [comment]
I found the problem, they disappeared after closing Generated Normals, but ComplementaryUnbound_r5.1.1.zip doesn't have this problem.

**Comment by DefinedAscent** [comment]
> I found the problem, they disappeared after closing Generated Normals, but ComplementaryUnbound_r5.1.1.zip doesn't have this problem.

This is what I have observed as well. I do not have the problem however with the previous versions of Euphoria Patches.

**Comment by SpacEagle17** [comment]
Would it be possible to share your settings file and also tell me what mod rendering specifically is affected to try and reproduce it?

**Comment by DefinedAscent** [comment]
> Would it be possible to share your settings file and also tell me what mod rendering specifically is affected to try and reproduce it?

[ComplementaryReimagined_r5.1.1 + EuphoriaPatches_1.2.txt](https://github.com/EuphoriaPatches/EuphoriaPatcher/files/14017482/ComplementaryReimagined_r5.1.1.%2B.EuphoriaPatches_1.2.txt)
If I had to guess based off the broken entities and how they look, they seem to be from Create. But I am using IDAS as well so it may be from those structures. As Qing said as well, it only happens with either coated textures or generated normals. But using just complementary shaders, everything is normal as it should be.

**Comment by SpacEagle17** [comment]
Hello everyone, the error does not seem to be on our side, but rather the dev developer of the flywheel compat mod has to add compatibility to Euphoria Patches. 
See more here: https://github.com/leon-o/iris-flw-compat/issues/89

**Comment by SpacEagle17** [comment]
Should be fixed with iris flywheel compat mod 1.1.2
