### ISSUE TITLE
Forge/Embeddium/Oculus 1.20.1: Lower than default generated normals interact strangely with lightmap normals

### ISSUE THREAD

**Issue by soup587** [EuphoriaPatches/EuphoriaPatcher#4]
title, seems like it's something with block tris given the way the normal difference seems to 'split' diagonally across a block

![2023-12-30_19 40 48](https://github.com/EuphoriaPatches/EuphoriaPatcher/assets/41347805/b1ea0c28-7519-46e0-9611-cacdffcd2c63)

**Comment by SpacEagle17** [comment]
This unfortunately is an issue that happens with all directional lightmap implementations and as far as I know, it can't be fixed. I tried to minimize it as much as possible
