### ISSUE TITLE
mod crashes servers when in mods folder. wrong envirtonment set in fabric.mod.json

### ISSUE THREAD

**Issue by Linguardium** [EuphoriaPatches/EuphoriaPatcher#5]
https://github.com/EuphoriaPatches/EuphoriaPatcher/blob/0e723ed76e954367ed15771272c37ed45647a604/src/main/resources/fabric.mod.json#L16

Setting environment to `client` will prevent the server from attempting to load the mod. Since the mod is not supported on servers, this is likely the best course of action.

**Comment by isuewo** [comment]
Yes, you're right. I should've thought about that. Thank you!

Fixed in https://github.com/EuphoriaPatches/EuphoriaPatcher/commit/ac943540b40f2d9104f72f5eb726cf82746594a0
