### ISSUE TITLE
Setting clouds to Vanilla breaks the shader

### ISSUE THREAD

**Issue by BobzBlue** [EuphoriaPatches/EuphoriaPatcher#8]
net.minecraft.class_2973: Invalid shaders/core/clouds_sodium.json: The call method_34416 is not cancellable.

If clouds are set to vanilla the entire shader fails to load. This behavior is not seen on default Complementary Reimagined. Attempting to use vanilla clouds also prevents the chat from rendering up until the game is restarted.

**Comment by SpacEagle17** [comment]
Would it be possible for you to share the settings file? So I can see if I already fixed it or not?

**Comment by BobzBlue** [comment]
[ComplementaryReimagined_r5.1.1 + EuphoriaPatches_1.2.txt](https://github.com/user-attachments/files/15540650/ComplementaryReimagined_r5.1.1.%2B.EuphoriaPatches_1.2.txt)
CLOUD_STYLE_DEFINE is set to 50

**Comment by SpacEagle17** [comment]
Thanks! I just found the issue and fixed it!
